# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 228959f3ec13fbf22ecf41e613e15c922d5e1b49811728fe1df374ffe7f676a5ca6dc9b062f02ecf861b6438b89c1f426f79361c2b853e4c42260f150da224f8

test:
  secret_key_base: 849f11f4978fbd60448db022e083ba63425863aa81c08fe7bea6571cdc0e4b124c25db4f174a63561b38c5a9863a30b4d65ff990fdb820360c7f248c47d0064b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
